FROM python:3.9

COPY docker/requirements/ /tmp/requirements/

RUN python -m pip install --upgrade pip
RUN python -m pip install -r /tmp/requirements/base.txt

COPY meteorites.db .

EXPOSE 8001

CMD ["datasette","-p","8001","-h","0.0.0.0","meteorites.db"]
